config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root 'home#index'

  # get "/jenis_pasien", to: "home#cek_jenis_pasien"
  
  # resources :antrian do
  #   collection do
  #     get :dokter
  #     get :jadwal_poli
  #     get :pasien_baru
  #   end
  # end
  

  # post "check_step_one", to: "antrian#identy_check"
  # get "check_step_one", to: "antrian#identy_check"

  # post "check_step_two", to: "antrian#destination_check"
  # post "check_step_three", to: "antrian#registration_check"
  # post "/batal_kunjungan", to: "antrian#kontrol_session"

  root 'qrcode#index'
  get "checkin", to: "qrcode#index"
  post "checkin", to: "qrcode#update"
  post "kewang", to: "qrcode#kewang"
  
  # get "/antrian/schedule"
  
  get "cetak_bukti", to: "cetakan#bukti_daftar"
  # post "cari", to: "cari#bukti_daftar"

  # dashboard TV
  # get "/dashboard/antrian", to: "dashboard#tampil"
  # get "/monitoring/antrian", to: "monitoring#index"

end

app/controllers/cetakan_controller.rb
class CetakanController < ApplicationController
    # layout "layouts/app-report"
    before_action :check_no_reservasi, only: :bukti_daftar

    def bukti_daftar

        if session['no_reservasi'].present?
            @reservasi = Regonline::Reservasi.find_by(ID: session['no_reservasi'])
        else
            @reservasi = Regonline::Reservasi.find_by(ID: params["data"])
        end 

        if @reservasi.present?                         
            session['no_reservasi'] = @reservasi.ID
            # qrcode(@reservasi.ID)

            generate_pdf
             
            # respond_to do |format|
                # format.html
                # format.pdf {
                #     send_data(receipt.render,
                #         filename: "bukti_daftar.pdf",
                #         type: "application/pdf",
                #         disposition: :inline,
                #         orientation:                    'Landscape',  
                #     )
                # }
                # format.pdf do
                #     render pdf: "bukti_daftar.pdf"   # Excluding ".pdf" extension.
                # end
            # end
        else
            # if session['jenis_pasien'] = 2
            #     redirect_to pasien_baru_antrian_index_path
            # elsif  session['jenis_pasien'] = 1
            #     redirect_to antrian_index_path
            # else
            #     redirect_to root_path
            # end
            redirect_to "https://rsupleimena.co.id"
        end
    end

    def cari
        reservasi = Regonline::Reservasi.find_by(NORM: params[:norm], TANGGAL_LAHIR: params[:tanggal_lahir])
        
        if reservasi.present?
            @reservasi = reservasi
            qrcode(@reservasi.ID)
        else !reservasi.present?
            redirect_to cari_path,  
                notice: "Maaf, norm atau tanggal lahir tidak sessuai",
                alert: "danger"
        end
        
    end

    private

        def generate_pdf
            respond_to do |format|
            format.pdf do
                render pdf: 'bukticetak',
                    template: 'cetakan/bukticetak'
            end
            end
        end


        # def qrcode(value)
        #     qrcode = RQRCode::QRCode.new("#{value}")
            
        #     png = qrcode.as_png(
        #         bit_depth: 1,
        #         border_modules: 4,
        #         color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        #         color: "black",
        #         file: nil,
        #         fill: "white",
        #         module_px_size: 6,
        #         resize_exactly_to: false,
        #         resize_gte_to: false,
        #         size: 120,
        #       )
        #   # Attach the QR code to the active storage
        #     #   self.qrcode.attach(
        #     #     io: StringIO.new(png.to_s),
        #     #     filename: "qrcode.png",
        #     #     content_type: "image/png",
        #     #   )
        #     #   # Attach the QR code to the active storage
        #     #   self.qrcode.attach(
        #     #     io: StringIO.new(png.to_s),
        #     #     filename: "qrcode.png",
        #     #     content_type: "image/png",
        #     #   )
        # end

        # def receipt
            
        #     Receipts::Register.new(
        #         details: [
        #         ["<b>Bukti Pendaftaran Online</b>"],
        #         ["No. Pendaftaran", @reservasi.ID ],
        #         ["Date paid", Date.today],
        #         ["Payment method", "ACH super long super long super long super long super long"]
        #         ],
        #         company: {
        #         name: "Example, LLC",
        #         address: "123 Fake Street\nNew York City, NY 10012",
        #         email: "support@example.com",
        #         logo: Rails.root.join("app/assets/images/rsjl.png"),
        #         banner: Rails.root.join("app/assets/images/fsh.png")
                
        #         },
        #         recipient: [
        #         "Customer",
        #         "Their Address",
        #         "City, State Zipcode",
        #         nil,
        #         "customer@example.org"
        #         ],
        #         line_items: [
        #         ["<b>Item</b>", "<b>Unit Cost</b>", "<b>Quantity</b>", "<b>Amount</b>"],
        #         ["Subscription", "$19.00", "1", "$19.00"],
        #         [nil, nil, "Subtotal", "$19.00"],
        #         [nil, nil, "Tax", "$1.12"],
        #         [nil, nil, "Total", "$20.12"],
        #         [nil, nil, "<b>Amount paid</b>", "$20.12"],
        #         [nil, nil, "Refunded on #{Date.today}", "$5.00"]
        #         ],
        #         footer: "Thanks for your business. Please contact us if you have any questions."
        #     )
        # end

        def check_no_reservasi
            # if session['no_reservasi'].present?
                @reservasi =  Regonline::Reservasi.find_by(ID: 2205110005) #session['no_reservasi'])
            # else
                # redirect_to antrian_index_path
            # end
        end

end

app/views/cetakan/bukti_daftar.html.erb
<turbo-frame id="jenis_pasien">
    
    <!-- import jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!--Modal JS Script -->
    <script type="text/javascript">
        window.onload = () => {
            $('#onload').modal('show');
        }
    </script>

    <div class="modal fade" id="onload" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"> <!-- Add this line to your code -->
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Yeay, Kamu berhasil mendaftar! 🎉</h5>
                </div>
                <div class="modal-body">
                    Silahkan <%= link_to "Download", cetak_bukti_path(:format => 'pdf'), target: :_blank, class: "btn btn-primary" %> bukti cetak. 
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div> 

    <div class=" d-block d-sm-none justify-content-center">
        <header class="d-flex bg-1  py-3">
            <%= render_qr_code("https://www.google.com/") %>
        </header>
    </div>

    <div class="container d-flex justify-content-center mt-3">
        <div class="card shadow" style="width: 75%;">
            
            <div class="bg-1 d-none d-sm-block card-header text-center text-bold text-white">
                <%= image_tag("rsjl-light.png", width: 350) %> 
            </div>
            
            <div class="card-body text-center">
                <h5 class="card-title">Bukti Pendaftaran Online</h5>
                
                <br>
                <figure class="text-center">
                    <blockquote class="blockquote">
                        <p></p>
                    </blockquote>
                    <figcaption class="blockquote-footer">
                    <cite class="text-danger">*</cite> Harap anda membawa bukti ini pada saat berkunjung.
                    </figcaption>
                </figure>

            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>No. Registrasi</b> : <%= @reservasi.ID %></li>
                <li class="list-group-item"><b>Nama</b> : <%= @reservasi.NAMA %></li>
                <li class="list-group-item"><b>Tempat/Tanggal Lahir</b> : <%= @reservasi.TEMPAT_LAHIR %>, 22 November 1997</li>
                <li class="list-group-item"><b>Poli </b>: <%= referensi_ruangan(@reservasi.POLI).DESKRIPSI %></li>
                <li class="list-group-item"><b>Dokter </b>: <%= @reservasi %></b></li>
                <li class="list-group-item"><b>Tanggal Kunjungan : </b><%= @reservasi.TANGGALKUNJUNGAN%></li>
            </ul>
            <div class="card-body">
                <%= link_to "Kembali", root_path, class: "btn btn-secondary", data: {turbo: false} %>
            </div>
        </div>
    </div>


</turbo-frame>

app/views/cetakan/bukticetak.pdf.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Bukti Cetak Antroll</title>
    <script type="text/javascript" src="https://unpkg.com/qr-code-styling@1.5.0/lib/qr-code-styling.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
   
        
    </style>
</head>

<body>

<%#= render_qr_code("https://www.google.com/") %>
<h4>Bukti Daftar Antrian Online <br> RSUP Dr. Johannes Leimena</h4>
 <hr>
<center>
     <img src="<%= "data:image/png;base64,#{Base64.encode64(rqrcode_generate(@reservasi.ID).to_s)}" %>" alt="QR Code" />
</center>
<style>
    table {
        border: none !important;
    }
</style>
Nama : <%= @reservasi.NAMA %>
<br>
No. Reg <%= @reservasi.ID %>
<br>
No. Antrian Poli : <%= @reservasi.ANTRIAN_POLI %>

<br>
<br>

   <p>
   <i> <i style="color: red;">*</i> Antrian Ini Hanya Berlaku
Sesuai Tanggal Kunjungan <i style="color: red;"><%= @reservasi.TANGGALKUNJUNGAN %></i>
<br>
<i style="color: red;">*</i> Batas Waktu Checkin Pukul 10.00 Pagi
   </p>



</body>

</html>